apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deployment-app
  template:
    metadata:
      name: deployment-pod
      labels:
        app: deployment-app
    spec:
      containers:
      - name: deployment-container
        image: amulyaproject/my-maven-project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: NodePort
  selector:
    app: deployment-app
  ports:
  - port: 80
    targetPort: 8080
